---
- name:  创建node_exporter用户
  user:
    name: node_exporter
    shell: /bin/false
    create_home: no

- name:  检查Node Exporter是否已安装
  command: systemctl is-active node_exporter
  ignore_errors: yes
  register: node_exporter_status
  changed_when: false

- name:  下载Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.10.2/node_exporter-1.10.2.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz
    checksum: "sha256:c46e5b6f53948477ff3a19d97c58307394a29fe64a01905646f026ddc32cb65b"
  when: node_exporter_status.failed or node_exporter_status.stdout != "active"

- name:  解压并安装
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt
    remote_src: yes
    creates: /opt/node_exporter-1.10.2.linux-amd64/node_exporter

- name:  创建软链接（幂等）
  file:
    src: /opt/node_exporter-1.10.2.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    state: link

- name:  创建systemd服务
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=node_exporter
      ExecStart=/usr/local/bin/node_exporter --collector.systemd --collector.processes
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: '0644'

- name:  启动服务
  systemd:
    name: node_exporter
    enabled: yes
    state: started
    daemon_reload: yes

# 仅对Rocky配置防火墙（允许Ubuntu IP访问9100）
- name:  配置Rocky防火墙（仅当是Rocky节点时）
  firewalld:
    rich_rule: "rule family='ipv4' source address='{{ hostvars['ubuntu'].ansible_default_ipv4.address }}' port protocol='tcp' port='9100' accept"
    permanent: yes
    state: enabled
    immediate: yes
  when: 
    - inventory_hostname in groups['rocky_nodes']
    - ansible_os_family == "RedHat"
  ignore_errors: yes
