---
- name:  创建alertmanager用户
  user:
    name: alertmanager
    shell: /bin/false
    create_home: no

- name:  检查Alertmanager是否已安装
  command: alertmanager --version
  ignore_errors: yes
  register: alertmanager_version
  changed_when: false

- name:  下载Alertmanager
  get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/v0.31.1/alertmanager-0.31.1.linux-amd64.tar.gz"
    dest: /tmp/alertmanager.tar.gz
    mode: '0644'
    timeout: 30
  when: >
    alertmanager_version.stdout is not search("0.31.1") or
    alertmanager_version.stderr is defined

- name:  解压
  unarchive:
    src: /tmp/alertmanager.tar.gz
    dest: /opt
    remote_src: yes
    creates: /opt/alertmanager-0.31.1.linux-amd64/alertmanager

- name:  创建软链接（幂等）
  file:
    src: /opt/alertmanager-0.31.1.linux-amd64/alertmanager
    dest: /usr/local/bin/alertmanager
    state: link
    force: yes

- name:  创建目录
  file:
    path: /etc/alertmanager
    state: directory
    owner: alertmanager
    group: alertmanager
    mode: '0755'

- name: 创建 Alertmanager 数据目录
  file:
    path: /var/lib/alertmanager
    state: directory
    owner: alertmanager
    group: alertmanager
    mode: '0755'

- name:  生成alertmanager.yml（敏感信息注入！）
  template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    owner: alertmanager
    group: alertmanager
    mode: '0600'
  no_log: true  # 防止密码泄露到日志

- name:  生成systemd服务
  copy:
    dest: /etc/systemd/system/alertmanager.service
    content: |
      [Unit]
      Description=Alertmanager
      After=network.target

      [Service]
      User=alertmanager
      Group=alertmanager
      ExecStart=/usr/local/bin/alertmanager \
        --config.file=/etc/alertmanager/alertmanager.yml \
        --storage.path=/var/lib/alertmanager
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: '0644'

- name:  启动服务
  systemd:
    name: alertmanager
    enabled: yes
    state: started
    daemon_reload: yes
