---
- name:  创建prometheus用户
  user:
    name: prometheus
    shell: /bin/false
    create_home: no

- name:  检查Prometheus是否已安装
  command: prometheus --version
  ignore_errors: yes
  register: prometheus_version
  changed_when: false

- name:  下载Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v3.10.0/prometheus-3.10.0.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz
    timeout: 200
  when: >
    prometheus_version.stdout is not search("3.10.0") or
    prometheus_version.stderr is defined

- name:  解压
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt
    remote_src: yes
    creates: /opt/prometheus-3.10.0.linux-amd64/prometheus
  when: >
    prometheus_version.stdout is not search("3.10.0") or
    prometheus_version.stderr is defined

- name:  创建软链接（幂等）
  file:
    src: /opt/prometheus-3.10.0.linux-amd64/prometheus
    dest: /usr/local/bin/prometheus
    state: link
    force: yes
  when: >
    prometheus_version.stdout is not search("3.10.0") or
    prometheus_version.stderr is defined

- name:  创建目录
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus
  when: >
    prometheus_version.stdout is not search("3.10.0") or
    prometheus_version.stderr is defined

- name:  部署告警规则文件
  template:
    src: alert_rules.yml.j2
    dest: /etc/prometheus/alert_rules.yml
    owner: prometheus
    group: prometheus
    mode: '0644'

- name:  生成prometheus.yml（动态targets！）
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'

- name:  生成systemd服务
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      After=network.target

      [Service]
      User=prometheus
      Group=prometheus
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus \
        --web.listen-address=0.0.0.0:9090
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: '0644'

- name:  启动服务
  systemd:
    name: prometheus
    enabled: yes
    state: started
    daemon_reload: yes
